export const USER_SET_PHONE = 'USER_SET_PHONE';
export const USER_CHANGE_PHONE = 'USER_CHANGE_PHONE';
export const USER_VERIFY_CODE = 'USER_VERIFY_CODE';
export const USER_CHANGE_CODE = 'USER_CHANGE_CODE';
export const USER_SET_HANDLE = 'USER_SET_HANDLE';
export const USER_CHANGE_HANDLE = 'USER_CHANGE_HANDLE';
export const USER_SET_SECRET = 'USER_SET_SECRET';
export const USER_CHANGE_SECRET = 'USER_CHANGE_SECRET';

export const APP_ERROR = 'APP_ERROR';